### ISSUE TITLE
Azure - Image Deprecation

### ISSUE THREAD

**Issue by Sl3ipnir-Sec** [Orange-Cyberdefense/GOAD#248]
When standing up the Azure instance using terraform at present it errors with:
` Error: creating Windows Virtual Machine: (Name "goad-vm-srv03" / Resource Group "GOAD"): compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="ImageVersionDeprecated" Message="The platform image 'MicrosoftWindowsServer:WindowsServer:2016-Datacenter:2016.127.20181122' is deprecated." Target="imageReference"
 Error: creating Windows Virtual Machine: (Name "goad-vm-dc03" / Resource Group "GOAD"): compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="ImageVersionDeprecated" Message="The platform image 'MicrosoftWindowsServer:WindowsServer:2016-Datacenter:2016.127.20181122' is deprecated." Target="imageReference"`

**Comment by vitalsecurity** [comment]
I just encountered this issue as well.  Currently updating deploy.tf from 2016.127.20181122 to 2019.0.20181122 .  I assume there was a reason for the different image use though.

**Comment by vitalsecurity** [comment]
Change 2016.127.20181122 references to 2016.127.20190115 in ad/GOAD/providers/azure/terraform/deploy.tf

**Comment by xelerated** [comment]
Still flops on that one │ Error: creating Windows Virtual Machine "goad-vm-dc03" (Resource Group "GOAD"): compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="ImageVersionDeprecated" Message="The platform image 'MicrosoftWindowsServer:WindowsServer:2016-Datacenter:2016.127.20190115' is deprecated." Target="imageReference"

**Comment by xelerated** [comment]
Has the same info I have in mine. its the 2019 not the 2016 causing issues.

**Comment by xelerated** [comment]
I just changed all windows_version to "latest" and they all work.

**Comment by Mayfly277** [comment]
also fixed in v3

**Comment by aliabdelmalek00** [comment]
hey team,
i still have this problem for srv02 and dc03 even i set "latest" on the version
is there any solution
